### ISSUE TITLE
Useless ingress.yaml

### ISSUE THREAD

**Issue by sam30606** [emqx/blog#1053]
File: [/zh/202012/access-emqx-in-kubernetes-cluster-through-nginx-ingress-controller.md](https://www.emqx.com/zh/blog/access-emqx-in-kubernetes-cluster-through-nginx-ingress-controller)

This is useless, tarffic won't pass through ingress.
```
# ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  name: emqx
spec:
  rules:
  - host: emqx.cn.iotdp.cn
    http:
      paths:
      - backend:
          serviceName: my-emqx
          servicePort: 18083
        path: /
      - backend:
          serviceName: my-emqx
          servicePort: 8083
        path: /mqtt

```
